In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Data.csv',encoding = "ISO-8859-1")

In [3]:
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [4]:
###Drop Nan Values
df=df.dropna()


In [5]:
X = df.iloc[:,2:27]

In [6]:
y = df["Label"]

In [7]:
# df_headlines = df.drop("Date","Lable")

In [8]:
# Removing punctuations
X.replace("[^a-zA-Z]"," ",regex=True, inplace=True)

# Renaming column names for ease of access
list1= [i for i in range(25)]
new_Index=[str(i) for i in list1]
X.columns= new_Index
X.head(5)



0  \
0  A  hindrance to operations   extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   
3                      Pilgrim knows how to progress   
4                               Hitches and Horlocks   

                                    1  \
0                           Scorecard   
1                 The best lake scene   
2  United s rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                               2  \
0                Hughes  instant hit buoys Blues   
1                  Leader  German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                               3  \
0       Jack gets his skates on at ice cold Alex   
1                                  Cheerio  boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                             4  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers  are you all whingers    

                                                   5  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees    
2                                England on the rack   
3  Auntie back in fashion  even if the dress look...   
4                                   Hollywood Beyond   

                                                 6  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees    
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                   7  \
0                  Gunners so wide of an easy target   
1                             Has Cubie killed fees    
2               Cullinan continues his Cape monopoly   
3  Hussain hurt by  shambles  but lays blame on e...   
4                   Whingers   a formidable minority   

                                                   8  \
0      Derby raise a glass to Strupar s debut double   
1  Hopkins  furious  at Foster s lack of Hannibal...   
2             McGrath puts India out of their misery   
3                      England s decade of disasters   
4                             Alan Parker   part two   

                                          9  ...  \
0  Southgate strikes  Leeds pay the penalty  ...   
1                    Has Cubie killed fees   ...   
2            Blair Witch bandwagon rolls on  ...   
3      Revenge is sweet for jubilant Cronje  ...   
4                 Thuggery  Toxins and Ties  ...   

                                                  15  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne  Australia    
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere   UDIs   

                                                  16  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa  Mexico    
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted   Chloe lunettes   

                                               17  \
0             Kohl s successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid  Spain    
3    

In [9]:
# Convertng headlines to lower case
for index in new_Index:
    X[index]=X[index].str.lower()
X.head(1)

0          1  \
0  a  hindrance to operations   extracts from the...  scorecard   

                                 2                                         3  \
0  hughes  instant hit buoys blues  jack gets his skates on at ice cold alex   

                                        4  \
0  chaos as maracana builds up for united   

                                                   5  \
0  depleted leicester prevail as elliott spoils e...   

                                  6                                  7  \
0  hungry spurs sense rich pickings  gunners so wide of an easy target   

                                               8  \
0  derby raise a glass to strupar s debut double   

                                          9  ...  \
0  southgate strikes  leeds pay the penalty  ...   

                                         15  \
0  flintoff injury piles on woe for england   

                                                  16  \
0  hunters threaten jospin with new battle of the...   

                                    17                                    18  \
0  kohl s successor drawn into scandal  the difference between men and women   

                                    19  \
0  sara denver  nurse turned solicitor   

                                               20  \
0  diana s landmine crusade put tories in a panic   

                                                  21                22  \
0  yeltsin s resignation caught opposition flat f...  russian roulette   

         23                  24  
0  sold out  recovering a title  

[1 rows x 25 columns]

In [10]:
headlines = []
for row in range(0,len(X.index)):
    headlines.append(' '.join(str(x) for x in X.iloc[row,0:25]))

In [11]:
len(headlines[36])

752

In [12]:
max = 0
index = 0
for i in range(len(headlines)):
  if len(headlines[i]) > max:
    max = len(headlines[i])
    index = i
    #print("max=",max,"index=",i)
max,index


(4424, 2388)

In [13]:
len(headlines[4097])

3246

In [14]:
import tensorflow as tf

In [15]:
tf.__version__

'2.12.0'

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
### Vocabulary size
voc_size=15000

In [18]:
import nltk
import re
from nltk.corpus import stopwords

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
# ### Dataset Preprocessing
# from nltk.stem.porter import PorterStemmer
# ps = PorterStemmer()
# corpus = []
# for i in range(0, len(messages)):
#     print(i)
#     review = re.sub('[^a-zA-Z]', ' ', messages['Title'][i])
#     review = review.lower()
#     review = review.split()

#     review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
#     review = ' '.join(review)
#     corpus.append(review)

In [21]:
# corpus

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in headlines]
onehot_repr[1]

[14187,
 12043,
 9762,
 10425,
 2037,
 8202,
 4475,
 8857,
 14177,
 4305,
 3332,
 12043,
 11363,
 11447,
 11345,
 10329,
 12075,
 14240,
 11345,
 10329,
 12075,
 14240,
 11345,
 10329,
 12075,
 14240,
 7171,
 3961,
 1440,
 9615,
 1727,
 4888,
 1706,
 2955,
 13052,
 11345,
 10329,
 12075,
 14240,
 1284,
 3938,
 1706,
 8871,
 9287,
 13104,
 4382,
 11042,
 13104,
 10967,
 5126,
 13104,
 10967,
 11042,
 13104,
 4382,
 8912,
 8782,
 5126,
 12372,
 4672,
 12623,
 14939,
 13990,
 12764,
 1706,
 14943,
 7458,
 894,
 13104,
 9342,
 3280,
 1440,
 7056,
 3856,
 12043,
 9669,
 13263,
 12043,
 1151,
 1706,
 9808,
 8903,
 6441,
 1207,
 10987,
 1205,
 1484,
 7913,
 14763,
 1727,
 3846,
 14939,
 9217,
 6532,
 9185,
 5828,
 6069,
 4023,
 11334,
 13518,
 4244,
 3332,
 6631,
 13518,
 5929,
 7490,
 12043,
 13978,
 10595,
 14939,
 12043,
 10224,
 12471,
 1919,
 9450,
 11885,
 3856,
 12057,
 6012,
 14946,
 6962,
 8118,
 7525,
 12192,
 7066,
 4729,
 12158,
 9410,
 12916,
 4470,
 5595,
 12043,
 7474,
 11722,


### Embedding Representation

In [23]:
sent_length=4430
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0 ... 11316  1284  9338]
 [    0     0     0 ...  7081 14939  2634]
 [    0     0     0 ...  7077  2134  4182]
 ...
 [    0     0     0 ... 14939  6875  6227]
 [    0     0     0 ... 13908  2780  3316]
 [    0     0     0 ...  3014  1284  4610]]


In [24]:
embedded_docs[2388]

array([    0,     0,     0, ...,  7063,   399, 11546], dtype=int32)

In [25]:
## Creating model
embedding_vector_features=20
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(40))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4430, 20)          300000    
                                                                 
 lstm (LSTM)                 (None, 40)                9760      
                                                                 
 dense (Dense)               (None, 1)                 41        
                                                                 
Total params: 309,801
Trainable params: 309,801
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
len(embedded_docs),y.shape

(4098, (4098,))

In [27]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [28]:
X_final.shape,y_final.shape

((4098, 4430), (4098,))

In [29]:
X_final

array([[    0,     0,     0, ..., 11316,  1284,  9338],
       [    0,     0,     0, ...,  7081, 14939,  2634],
       [    0,     0,     0, ...,  7077,  2134,  4182],
       ...,
       [    0,     0,     0, ..., 14939,  6875,  6227],
       [    0,     0,     0, ..., 13908,  2780,  3316],
       [    0,     0,     0, ...,  3014,  1284,  4610]], dtype=int32)

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [31]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
43/43 [==============================] - 23s 377ms/step - loss: 0.6916 - accuracy: 0.5337 - val_loss: 0.6945 - val_accuracy: 0.5144
Epoch 2/10
43/43 [==============================] - 14s 324ms/step - loss: 0.6741 - accuracy: 0.5650 - val_loss: 0.7171 - val_accuracy: 0.4959
Epoch 3/10
43/43 [==============================] - 17s 386ms/step - loss: 0.5303 - accuracy: 0.7978 - val_loss: 0.7736 - val_accuracy: 0.5129
Epoch 4/10
43/43 [==============================] - 13s 303ms/step - loss: 0.3430 - accuracy: 0.8791 - val_loss: 0.8604 - val_accuracy: 0.5129
Epoch 5/10
43/43 [==============================] - 11s 266ms/step - loss: 0.1700 - accuracy: 0.9654 - val_loss: 1.0525 - val_accuracy: 0.5078
Epoch 6/10
43/43 [==============================] - 13s 310ms/step - loss: 0.0630 - accuracy: 0.9902 - val_loss: 1.2645 - val_accuracy: 0.5115
Epoch 7/10
43/43 [==============================] - 12s 274ms/step - loss: 1.1979 - accuracy: 0.7639 - val_loss: 2.4961 - val_accuracy: 0.4856

In [32]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [36]:
y_pred=model.predict(X_test)

43/43 [==============================] - 5s 83ms/step


In [41]:
y_pred[1][0]

0.49999452

In [47]:
for i in range(len(y_pred)):
  if y_pred[i][0]<0.5:
    y_pred[i][0] = 0
  else :
    y_pred[i][0] = 1


1
2
3
5
6
8
10
14
17
18
22
23
27
29
30
31
33
34
36
37
38
39
40
41
42
44
45
46
47
49
50
53
54
55
56
58
61
62
64
65
67
70
71
72
75
76
79
80
81
83
86
89
90
91
93
95
99
103
108
110
111
112
113
115
117
119
122
124
125
127
128
130
131
132
133
134
135
136
138
140
142
144
148
153
156
159
160
161
163
164
166
167
168
170
172
174
177
180
182
183
184
185
187
189
190
193
194
195
196
200
202
206
207
208
211
212
215
216
217
218
220
222
223
224
226
230
231
236
237
238
242
243
244
245
246
251
253
255
256
257
259
260
266
272
273
274
276
278
279
281
282
283
284
286
287
288
289
290
292
295
297
299
301
303
304
306
307
312
317
318
322
323
324
326
330
334
335
336
337
342
344
348
349
350
351
353
354
355
359
360
364
366
372
373
374
378
379
381
382
383
386
387
390
393
394
395
396
397
399
401
403
405
406
407
410
412
413
416
420
423
424
426
429
430
431
432
433
434
442
443
447
451
457
458
459
460
461
462
463
465
470
475
476
480
481
482
483
485
486
487
489
490
494
495
497
502
503
504
505
507
510
513
514
516
517
518

In [48]:
y_pred

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [49]:
from sklearn.metrics import confusion_matrix

In [50]:
confusion_matrix(y_test,y_pred)

array([[339, 318],
       [348, 348]])

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5077605321507761